### ISSUE TITLE
add CI checks for API docs building and PyPI tar.gz file building

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#125]
On each commit to dev, there should be a GitHub action that tries to build the API docs and the scadnano-x.x.x.tar.gz file that is uploaded to PyPI. This way, if either of these fails, we know that the docs or PyPI package action will fail when committed to master. 

The checks could pass and the action on commit to master could still fail, but at least this way it would not be because the files simply could not be generated.

**Comment by UnHumbleBen** [comment]
I think there should be two separate actions since API docs building and package building are separate independent tasks. One checks for API docs build and the other checks for package build.

**Comment by dave-doty** [comment]
> I think there should be two separate actions since API docs building and package building are separate independent tasks. One checks for API docs build and the other checks for package build.

Sounds good.

**Comment by UnHumbleBen** [comment]
Do you know a quick way to make the docs and/or the package build fail? Want to test out the actions.

**Comment by dave-doty** [comment]
The docs print errors/warnings in red; not sure how to check if they failed. Maybe there's a return code.

Find any Sphinx command in the docstrings, e.g., `` :any:`Domain` ``, and mess it up, e.g., `` :anyy:`Domain` ``

**Comment by dave-doty** [comment]
For the PyPi build, I'm not sure.
