### ISSUE TITLE
automatically install dataclass backport for Python 3.6

### ISSUE THREAD

**Issue by tcosmo** [UC-Davis-molecular-computing/scadnano-python-package#134]
Get inspired by:
https://github.com/samuelcolvin/pydantic/blob/645e5fe6a0c74c95c24410571e9bb804af3eb677/setup.py#L97

**Comment by tcosmo** [comment]
Solved with : 11028041680e1f8e5595fed67df9f8ba31e95d9e
I tested it it works well.

@dave-doty : question on the side, I see no minimal python version requirement for the package in setup.py, shoud not we require python 3.6 at minima?

**Comment by dave-doty** [comment]
> @dave-doty : question on the side, I see no minimal python version requirement for the package in setup.py, shoud not we require python 3.6 at minima?

Yes, if we can, let's require Python 3.6 as a minimum.

**Comment by tcosmo** [comment]
Solved with 1999445cc1e09db2e15fb43a3b7763ef242109db

**Comment by dave-doty** [comment]
Thanks!

If possible, can you reference the issue in the commit message when it is closed?

https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

That way GitHub will close the issue automatically when the changes are merged in the master branch. Also the commit message shows up in the automatically generated release notes: https://github.com/UC-Davis-molecular-computing/scadnano-python-package/releases
