### ISSUE TITLE
implement oxDNA export

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#139]
This code has been implemented by Daniel Hader and Matt Patitz. Ideally, we will incorporate it into the scadnano.py file, so that it can be called with a single method like this:

```python
import scadnano

design = scadnano.Design()
# ...
oxdna_content = design.export_to_oxdna()
with open('oxdna.???', 'w') as f:
    f.write(oxdna_content)
```

**Comment by dave-doty** [comment]
There's a complication: scadnano uses left-handed coordinates, but oxDNA might use right-handed coordinates:

https://www.evl.uic.edu/ralph/508S98/coordinates.html

I'm not sure how to think about this.

**Comment by UnHumbleBen** [comment]
> There's a complication: scadnano uses left-handed coordinates, but oxDNA might use right-handed coordinates:
> 
> https://www.evl.uic.edu/ralph/508S98/coordinates.html
> 
> I'm not sure how to think about this.

After merging PR https://github.com/UC-Davis-molecular-computing/scadnano/pull/499, scadnano now uses a right-handed coordinate system
