### ISSUE TITLE
store DNA sequence in domains and loopouts, not in strand

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#149]
Currently, a strand either has a DNA sequence assigned or not. This makes it awkward to implement an issue like https://github.com/UC-Davis-molecular-computing/scadnano/issues/425, assigning a sequence to just one domain/loopout, where `?` symbols must be assigned to domains/loopouts on the remainder of the strand.

Also, it is awkward to do calculation, since in the immutable built values Dart stores, a Strand has a reference to its Domains/Loopouts, but not the other way around. So if sequence were stored in domains, it would still be easy to calculate the DNA sequence for the whole Strand. But currently it is awkward to access the sequence of a Domain if there is no reference to the parent Strand.

This issue proposes storing the DNA sequence in the Domains/Loopouts, not only in the Dart objects, but in JSON as well.

See also https://github.com/UC-Davis-molecular-computing/scadnano/issues/492.

**Comment by UnHumbleBen** [comment]
@dave-doty Should we introduce the breaking change that the `dna_sequence` in Strand constructor will no longer be valid? Example:
```py
sc.Strand([
    sc.Domain(0, True, 0, 3),
    sc.Domain(1, False, 0, 3),
    sc.Domain(2, True, 0, 3),
], dna_sequence='ACA TCT GTG'.replace(' ', ''))
```

Currently, the constructor is generated by dataclasses, but if we replace the dna_sequence field with a getter function, then this field no longer can be set, so we would need to write our own `__init__` to preserve the functionality.

**Comment by dave-doty** [comment]
Hmm, we will have to write a custom `Strand.__init__()`. That seems a natural thing to do in the constructor, and I don't want to introduce a breaking change if we can handle it.
