### ISSUE TITLE
remove Helix.pitch and Helix.yaw

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#163]
Currently, both a HelixGroup and and Helix can have a pitch and yaw unequal to 0, but this is not recommended. It is recommended that only HelixGroups have nonzero pitch and yaw. If you want to make two Helices not parallel, the recommended way is to put them in separate HelixGroups, where all Helices in the HelixGroup are parallel.

This issue proposes a breaking change to codify this into a requirement by removing the fields Helix.yaw and Helix.pitch. Add methods to Design to look up the yaw and pitch of a Helix, which will delegate to the HelixGroup's property. But the only way make two helices non-parallel is to put them in separate groups.

The interpretation of the order in which to evaluate these (see #150 for explanation of this detail) remains yaw, then pitch, then roll. Although both a HelixGroup and Helix can have a nonzero roll, since it is applied last, it doesn't matter which order the two rolls are applied: the total roll of a Helix is simply `Helix.roll` + `HelixGroup.roll`.

**Comment by UnHumbleBen** [comment]
Tentative release note:

# Release Note:

**Breaking Change:** The field `Helix.pitch` and `Helix.yaw` has been removed to ensure that all helices within a `HelixGroup` are parallel. 

If you want to set `pitch` and `yaw` for a helix, put them into a `HelixGroup` with the desired pitch/yaw.

```python
# old
helix = sc.Helix(pitch=90)


# new
pitch90_helix_group = sc.HelixGroup(pitch=90)
helix = sc.Helix(group='pitch90')
```

If you want to look up `pitch` and `yaw` of a helix, use ...

TODO

**Comment by UnHumbleBen** [comment]
@dave-doty To support older versions, if user import a design with helices with individual pitch and yaw, we should generate helix groups for these helices. Any suggestion for how to go about doing this? (I guess technically, this is an issue for the web app)

One (lazy) way could simply be making a helix group for every single helix and the helix group would have the pitch and yaw values of the individual helix.

Another way would be to use a dictionary mapping each (pitch, yaw) tuple to a list of helices with those (pitch, yaw) values. Then place each helix with the same pitch and yaw values into the same helix group named something like `pitch_{pitch}_yaw_{yaw}`.

In any case, I'm not sure how to handle the case where both pitch and yaw are set on the group level as well as helix level. 

What do you think?

**Comment by dave-doty** [comment]
> @dave-doty To support older versions, if user import a design with helices with individual pitch and yaw, we should generate helix groups for these helices. Any suggestion for how to go about doing this? (I guess technically, this is an issue for the web app as well)
> 
> One (lazy) way could simply be making a helix group for every single helix and the helix group would have the pitch and yaw values of the individual helix.

No, don't do this.
 
> Another way would be to use a dictionary mapping each (pitch, yaw) tuple to a list of helices with those (pitch, yaw) values. Then place each helix with the same pitch and yaw values into the same helix group named something like `pitch_{pitch}_yaw_{yaw}`.

Yes, this sounds good.


> In any case, I'm not sure how to handle the case where both pitch and yaw are set on the group level as well as helix level.

You can just add the group angle to the helix angle in this case.

But some care is still required. I think the following sounds reasonable:

- If they are using a single HelixGroup, but some Helices have non-zero pitch and/or yaw, then make new HelixGroups. (Be sure to add the angles from the HelixGroup to the angles in the Helices, in case it is non-zero) Definitely don't put the Helices all in separate groups if they have the same pitch and yaw. Test for approximate equality and make only as many HelixGroups as there are distinct values (within some floating-point error)
- If they are using multiple helix groups, but they set pitch and yaw for individual Helices within the HelixGroup, but it's the same pitch and yaw (approximately), then simply add that pitch and yaw to the pitch and yaw of the HelixGroup.
- In any other case report an error and say that the user is required to do the translation before the design can be loaded. I think the following is the only remaining case: They use multiple HelixGroups, and within some HelixGroup, they assign significantly different `pitch` or `yaw` values to two different Helices. In this case, they obviously mean for the different HelixGroups to mean something, so we don't want to destroy their HelixGroups automatically. (In the first case, if they only have one HelixGroup, then we aren't disrupting any structure they had already by making more HelixGroups.)
