### ISSUE TITLE
support Extensions on the end of a Strand

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#2]
This gives a nice way to specify toeholds and extensions common in DNA strand displacement designs.

See also https://github.com/UC-Davis-molecular-computing/scadnano/issues/34.

This is not supported currently in scadnano, and it will take a lot of effort to support it, since much of the logic pervading the code assumes the first and last substrands are `Domain`'s. There's nothing requiring this in principle, but it will be a headache to change it. Also, some design decisions will have to be made along the way. 

For example, the default staple name for exporting sequences is the same as cadnano, where the staple is named after the (helix,offset) pairs of its 5' and 3' ends. We could do the same thing, where if the end of a strand is a `Loopout`, we use the adjacent `Domain`'s to name the staple. But little decisions like this will probably have to happen all over the place.

**Comment by dave-doty** [comment]
> @dave-doty For the JSON, we can represent, extensions in similar format as Loopout
> 
> ```json
> {
>   "extension": <length>
> }
> ```
> 
> Do you think this is a good representation?

Yes, that's perfect.

**Comment by UnHumbleBen** [comment]
# Release Note
## Introducing DNA `Extension` API
DNA Extensions can now be represented. This gives a nice way to specify toeholds and extensions common in DNA strand displacement designs.

They can be created using the `Extension` class.

```python
import scadnano as sc

domain = sc.Domain(helix=0, forward=True, start=0, end=10)
toehold = sc.Extension(num_bases=5)
strand = sc.Strand([domain, toehold])
```

It can also be created with chained method calls

```python
import scadnano as sc

design = sc.Design(helices=[sc.Helix(max_offset=10)])
design.draw_strand(0,0).move(10).extension_3p(5)
```

**Comment by dave-doty** [comment]
@UnHumbleBen 

I edited the example a bit to show 5' and 3' extensions; does the code look correct?

**Comment by UnHumbleBen** [comment]
Yup looks correct
