### ISSUE TITLE
support Extensions in oxDNA export 

### ISSUE THREAD

**Issue by cgevans** [UC-Davis-molecular-computing/scadnano-python-package#240]
Extensions are currently assumed to be loopouts in the oxDNA export code, causing it to fail.

**Comment by dave-doty** [comment]
Yeah, sorry, the extension support is very preliminary right now. I need to figure out a good way to do this, and also loopouts, which have a problem we discovered at DNA 28 when there are too many bases in too short a distance and it explodes the oxDNA dynamics simulation.

**Comment by cgevans** [comment]
>But I'm hoping this might not be too bad to support. Perhaps a good algorithm is just to draw the extension as a straight line with reasonable inter-base distance, going out perpendicular from the helix, based on the helix roll.

That's what I'm currently playing with, somewhat ineptly, and it doesn't seem too bad: while my current code is doing some things that are clearly wrong in oxview, but they seem to largely correct themselves with a few hundred MC steps.  Loopouts seem trickier.
