### ISSUE TITLE
import/export cadnano file format

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#3]

**Comment by tcosmo** [comment]
Both features are implemented and work well on what they are tested on.
Remain to do:
more import tests and some doc.

T

**Comment by dave-doty** [comment]
Closed in 5f581429180cefdca543cb42c4609607ef9342f7

**Comment by tcosmo** [comment]
All cadnano designs can (in theory) be imported to scadnano. (I think I have experienced one bug in a design when trying to import a 1 base unit scaffold but cannot reproduce.)

However not all scadnano designs are exportable to cadnano and all the details are given here on the conditions to comply with 

(TLDR: do not use feature that doesnt exists in cadnano and respect the arbitrary cadnano's system where the parity of the helix dictates if the scaffold goes forward or backward):

https://scadnano-python-package.readthedocs.io/en/latest/#interoperability-cadnano-v2
