### ISSUE TITLE
cadnano_v2 import of squarenut design adds extra strands

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#34]
In [this paper](https://www.nature.com/articles/nature08016), SI Figure S5 shows a "squarenut design". It is available as a cadnano file [here](https://www.dropbox.com/s/zsm3xlnyurnffd9/Nature09.zip?file_subpath=%2FNature09).

I put together a zip file [squarenut.zip](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/files/4536255/squarenut.zip) with three files: the cadnano `squarenut.json` file, the imported scadnano `squarenut.dna` file, and the SVG image `squarenut.svg` showing how the design should appear in cadnano.

This is what the first two helices look like in the SVG file (but there are similar problems in every helix)

![image](https://user-images.githubusercontent.com/19274365/80320492-8e13e200-87cb-11ea-9bee-1d6f1877d5e6.png)

This is how they appear in scadnano:

![image](https://user-images.githubusercontent.com/19274365/80320537-d7fcc800-87cb-11ea-8a19-5645d65591e9.png)

As you can see, there are extra staple strands on the left and right ends of the two helices (in red in scadnano). Each appears to be confined to a single helix, but have long-range horizontal crossovers from one side of the helix to the other.

In the file `squarenut.dna`, here are the two extra strands on helix 0:

```json
{
  "color": "#cc0000",
  "substrands": [
    {"helix": 0, "forward": false, "start": 9, "end": 35},
    {"helix": 0, "forward": false, "start": 133, "end": 135}
  ]
}
```

and

```json
{
  "color": "#cc0000",
  "substrands": [
    {"helix": 0, "forward": false, "start": 112, "end": 133}
  ]
},
```

**Comment by tcosmo** [comment]
Their SVG is not consistent with there cadnano design.
Cf: screenshot attached.

However the scadnano conversion is consistent with the cadnano design.
![Screenshot from 2020-04-27 09-39-40](https://user-images.githubusercontent.com/7616128/80352018-29a85f80-886b-11ea-82f9-11e0cfa0cbb6.png)

**Comment by dave-doty** [comment]
Okay, I'll assume this was a bug in the cadnano design.
