### ISSUE TITLE
from_cadnano_v2 keyerror: 'vstrands'

### ISSUE THREAD

**Issue by jcalumba** [UC-Davis-molecular-computing/scadnano-python-package#35]
I've got a simple scadnano script to load a .dna file and write the corresponding cadnano .json file in the same directory, which can be found here: https://github.com/jcalumba/oxdna_relax/blob/master/export.py .
My example .dna file can be found here:
https://github.com/jcalumba/oxdna_relax/blob/master/export.dna .

When I try to run this script with any given *.dna file, I get the following error:
C:\Users\jcalumba\scadnano\scadnano-python-package\scadnano\backup>python ../export.py export.dna
2​
Traceback (most recent call last):​
  File "../export.py", line 16, in <module>​
    origami = design.from_cadnano_v2('.', name)​
  File "C:\Users\jcalumba\scadnano\scadnano-python-package\scadnano\scadnano.py", line 2207, in from_cadnano_v2​
    num_bases = len(cadnano_v2_design['vstrands'][0]['scaf'])​
KeyError: 'vstrands' 

To fix it, I tried to pass in an empty list of vstrands when I instantiated my DNAdesign object, seen here:
    design = sc.DNADesign(helices=[], strands=[], vstrands=[], grid=sc.square)

but got a keyword error:

  File "../export.py", line 15, in <module>
    design = main()​
  File "../export.py", line 5, in main​
    design = sc.DNADesign(helices=[], strands=[], vstrands=[], grid=sc.square)​
TypeError: __init__() got an unexpected keyword argument 'vstrands'

**Comment by dave-doty** [comment]
This isn't a bug. The method `from_cadnano_v2` is a static method intended to read a cadnano `.json` file and return a scadnano `DNADesign` object. It won't work if you give it a scadnano `.dna` file.

Perhaps you want to export the `.dna` file to a cadnano `.json` file. To do that, call `design.export_cadnano_v2()`.

**Comment by jcalumba** [comment]
That worked, thanks for clearing that up.
________________________________
