### ISSUE TITLE
imported cadnano design fails to export

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano-python-package#70]
Importing this cadnano design in the web interface, and then exporting it to cadnano, fails with the error

    Error exporting file: '>' not supported between instances of 'NoneType' and 'int'

I haven't tried it yet from the command line with the Python library directly.

cadnano file attached as zip.

[Double Layer Origami 12 LQ edits.zip](https://github.com/UC-Davis-molecular-computing/scadnano-python-package/files/4709244/Double.Layer.Origami.12.LQ.edits.zip)

**Comment by tcosmo** [comment]
That is a bug in the code which populates a design from a .dna file, the `from_json` cascade.

**Comment by tcosmo** [comment]
Ok, that bug was there in the version that the server was running but does not seem to be on master anymore. The issue should disapear when updating the server.

**Comment by dave-doty** [comment]
Do you know the source of the bug? I ran into it when running on the web app, which didn't give much information. It just popped up the error message I quoted, but there was no stack trace or anything, so I didn't track down which line caused it. 

It would be good to add a unit test that reproduces the bug (on an old commit) if possible, to ensure it stays away in the future.

In the mean time I'll modify the web app to print more detail in an error message.

**Comment by dave-doty** [comment]
fixed in #71
